Project details popup
egichuhis/Edwin-Portfolio pull request #21
Opened 2023-04-18 17:28 UTC by egichuhis

Hello, kindly review this PR.

### CHANGES

- Add project details popup window
- Add Javascript functionality to toggle project popup window

Thank you.

2023-04-18 19:05 UTC, LionRouge1 requested changes
Hi @egichuhis, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Followed Javascript best practices :+1: 
- Code clean and easy to understand :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
[OPTIONAL]
- [ ] On a large screen, the bar separating the language, frameworks, and skills with their details overlaps (see image). Please check it.

![Screenshot from 2023-04-18 18-50-50](https://user-images.githubusercontent.com/91142432/232878923-6b345e7d-0d35-47e8-b2d7-82050eb625ce.png)


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 19:05 UTC, LionRouge1 commented on style.css
> +}
- [x] Nice work implementing popup windows :clap: :sunglasses: However your popup design looks different compared to the Figma design for the both mobile and desktop versions (see images). Kindly, add space around the popup windows to follow the Figma design as requested in the project requirement.

### Mobile version :point_down: 
<table>
  <tr>
    <th>Your Design</th>
    <th>Figma's Design</th>
  <tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/91142432/232865379-a8df29f6-84cc-4e37-9d01-4f66df76dae9.png"/></th>
    <th><img src="https://user-images.githubusercontent.com/91142432/232865341-8ff32abf-67cb-45c4-b797-622ca695b0da.png"/></th>
  <tr>
</table>

### Desktop version :point_down: 
<table>
  <tr>
    <th>Your Design</th>
    <th>Figma's Design</th>
  <tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/91142432/232865599-a2424532-a283-4ca5-8861-3a286e07c30d.png"/></th>
    <th><img src="https://user-images.githubusercontent.com/91142432/232865579-66af532d-edb2-4c38-95e5-0ac5c808e2e4.png"/></th>
  <tr>
</table>

2023-04-18 19:05 UTC, LionRouge1 commented on script.js
>  }
- [x] This code will add the same card (project) 5 times and adding another project in the future will be a little bit challenging. Therefore I suggest you create an array of objects to store JavaScript objects containing the information for each project.

e.g: 
```sh
const projects = [
    {
        name: "project 1 name",
        description: "project 1 description",
        image: "link_to_poject1_image.jpg",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        link: "link_to_live_version.com",
        ...
    },
    {
        name: "project 2 name",
        description: "project 2 description",
        image: "link_to_poject2_image.jpg",
        technologies: ["REACT", "CSS","REDUX"],
        link: "link_to_live_version.com",
        ...
    },
    ...]
```

2023-04-18 19:05 UTC, LionRouge1 commented on index.html
>          </div>
- [x] Kindly make sure that the popup windows data is populated with the data from the projects on which the user clicked. That will make your popup windows dynamic.

2023-04-22 12:28 UTC, egichuhis commented on style.css
> +}
Done. Thanks

2023-04-22 16:15 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 16:16 UTC, merged